import {
  WordSearchMaster,
  CandyCrushGame,
  FaceNameMemoryGame,
  CastleDefenderGame,
  TapMinesweeperGame,
  RiverCrossingGame,
  WordChainLogicGame,
  SequenceRecallGame,
  BorderlineBrainsGame,
  MemoryTownBuilderGame,
  MaskMemoryGame,
  LogicGridSolverGame,
  TapChallengeGame,
  StopSignalGame,
  TrainOfThoughtGame,
  ShopShiftGame,
  TugOfMathsGame,
  TowerOfHanoi,
  BallSortGame,
  TileAdjustGame,
  CocktailSortGame,
  DataStreamSecurityGame,
  FishermansCatchGame,
  MarketRushGame,
  WhoIsBrainGame,
  ColorWordMatch,
  PatternMatchGame,
  ColorMatchCircleGame,
  MirrorMatchGame,
  NumberPuzzleGame,
} from '../pages';

export const gameRoutes = [
  { path: '/games/word-search-master-game', element: <WordSearchMaster />, name: 'Word Search Master Game' },
  { path: '/games/candy-crush-game', element: <CandyCrushGame />, name: 'Candy Crush Game' },
  { path: '/games/face-name-memory-game', element: <FaceNameMemoryGame />, name: 'Face Name Memory Game' },
  { path: '/games/castle-defender-game', element: <CastleDefenderGame />, name: 'Castle Defender Game' },
  { path: '/games/mine-sweeper-game', element: <TapMinesweeperGame />, name: 'Mine Sweeper Game' },
  { path: '/games/river-crossing-game', element: <RiverCrossingGame />, name: 'River Crossing Game' },
  { path: '/games/word-chain-logic-game', element: <WordChainLogicGame />, name: 'Word Chain Logic Game' },
  { path: '/games/sequence-recall-game', element: <SequenceRecallGame />, name: 'Sequence Recall Game' },
  { path: '/games/borderline-brains-game', element: <BorderlineBrainsGame />, name: 'Borderline Brains Game' },
  { path: '/games/memory-town-builder-game', element: <MemoryTownBuilderGame />, name: 'Memory Town Builder Game' },
  { path: '/games/mask-memory-game', element: <MaskMemoryGame />, name: 'Mask Memory Game' },
  { path: '/games/logic-grid-solver-game', element: <LogicGridSolverGame />, name: 'Logic Grid Solver Game' },
  { path: '/games/tap-challenge-game', element: <TapChallengeGame />, name: 'Tap Challenge Game' },
  { path: '/games/stop-signal-game', element: <StopSignalGame />, name: 'Stop Signal Game' },
  { path: '/games/train-of-thought-game', element: <TrainOfThoughtGame />, name: 'Train of Thought Game' },
  { path: '/games/shop-shift-game', element: <ShopShiftGame />, name: 'Shop Shift Game' },
  { path: '/games/tug-of-maths-game', element: <TugOfMathsGame />, name: 'Tug of Maths Game' },
  { path: '/games/tower-of-hanoi-game', element: <TowerOfHanoi />, name: 'Tower of Hanoi' },
  { path: '/games/ball-sort-game', element: <BallSortGame />, name: 'Ball Sort Game' },
  { path: '/games/tile-adjust-game', element: <TileAdjustGame />, name: 'Tile Adjust Game' },
  { path: '/games/cocktail-sort-game', element: <CocktailSortGame />, name: 'Cocktail Sort Game' },
  { path: '/games/data-stream-security-game', element: <DataStreamSecurityGame />, name: 'Data Stream Security Game' },
  { path: '/games/fishermans-catch-game', element: <FishermansCatchGame />, name: "Fisherman's Catch Game" },
  { path: '/games/market-rush-game', element: <MarketRushGame />, name: 'Market Rush Game' },
  { path: '/games/who-is-brain-game', element: <WhoIsBrainGame />, name: 'Who Is Brain Game' },
  { path: '/games/color-word-match-game', element: <ColorWordMatch />, name: 'Color Word Match Game' },
  { path: '/games/pattern-match-game', element: <PatternMatchGame />, name: 'Pattern Match Game' },
  { path: '/games/color-match-circle-game', element: <ColorMatchCircleGame />, name: 'Color Match Circle Game' },
  { path: '/games/mirror-match-game', element: <MirrorMatchGame />, name: 'Mirror Match Game' },
  { path: '/games/number-puzzle-game', element: <NumberPuzzleGame />, name: 'Number Puzzle Game' },
];
